# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59c3f710d08b7a8c0de858b9cbd495eff930b8970ee81cc388c7abb079facf898a08c818cc6baa67b1246eccc353b30f6af97a8fffa87635bc530eb29fac958c

test:
  secret_key_base: 542be0c2b35b25be4e3f14fed573881228284eaa308e2276bd040775f7c26d77361f146e5469250c6f7beba1babe6755bbb70733f3bd4cac7e5cfab1669297ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
